[versions]
minecraft = "1.9.4"
fabric-loom = "1.11-SNAPSHOT"
fabric-loader = "0.10.7"
yarn = "1.9.4+build.604"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
yarn = { group = "net.legacyfabric", name = "yarn", version.ref = "yarn" }

[plugins]
fabric-loom = { id = "legacy-looming", version.ref = "fabric-loom" }
