[versions]
minecraft = "1.21.2"
fabric-loom = "1.11-SNAPSHOT"
fabric-loader = "0.10.7"
yarn = "1.21.2+build.1"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
yarn = { group = "net.fabricmc", name = "yarn", version.ref = "yarn" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
